### ISSUE TITLE
Implement an API more aligned with Elixir style

### ISSUE THREAD

**Issue by BasileNouvellet** [IvanRublev/Domo#7]
Hey, thanks for this great library!

I was wondering if you would consider implementing an API more aligned with Elixir style, such as below:
- adding an alias `new/2` for `new_ok/2`
- adding an alias `ensure_type/2` for `ensure_type_ok/2`

This would allow to have an API in the shape of `function!/1` and `function/2` instead of `function!/1` and `function_ok/2`, which I guess would be more aligned with Elixir coding guidelines.

Example : [Ecto.insert/2](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert/2)

I can open a PR if you'd like.

**Comment by IvanRublev** [comment]
Hey, thanks for the feedback.
Yes, these `_ok` function names can be aligned with the standard notation indeed!
And in case if somebody needs to change a name due to a clash, there is a global config option `name_of_new_function`.

I think it would be good to drop the `_ok` postfix to have `new` and `new!` function names generated.
It'd be nice if you could make a PR for this.

**Comment by IvanRublev** [comment]
Updated to `new` and `new!` in [version 1.4.0](https://hex.pm/packages/domo/1.4.0) 

Please, search and replace `new_ok(` -> `new(` in all files of the project using Domo to migrate.

**Comment by BasileNouvellet** [comment]
Hey, sorry for my late reply, I was off last week.
Thank you for the update!
