### ISSUE TITLE
Is there a way to avoid the default values validation during the compilation?

### ISSUE THREAD

**Issue by hAdamm** [IvanRublev/Domo#9]
Hello and thanks for this library. I very much appreciate the effort and time you have put into this library. 

I have a question. Is there a way to avoid the default values validation during the compilation?

I do not need default values; So I have defined the struct with default nil values for each attribute. But the type I have defined includes some mandatory attributes. I received the error "Invalid value nil for field :name of %TestApp.User{}. Expected the value matching the <<_::_*8>> type." during the compilation. 

I want only to validate data during the struct creation. I do not need to validate the default values because they can be incomplete, like in my case.

Thank you for your answer.

**Comment by IvanRublev** [comment]
Hey, thanks for the good words.

The library validates struct defaults to guarantee the valid state when the struct is instantiated with `%User{}` syntax.
Giving no default values at all sets them to nil and causes the failure of the compilation due to type spec mismatch.

Sometimes valid default values may not be known at the compile-time and such failure doesn't fit 🙂
That can be addressed in the following alternative ways:
1. Support the `nil` values with `name: String.t() | nil` definition in type spec explicitly.
2. Configuring the library to skip this kind of validation for the given struct with `use Domo, ensure_struct_defaults: false`
3. Disable the struct defaults validation for the whole project by adding `config :domo, :ensure_struct_defaults, false` into `config.exs`.

**Comment by hAdamm** [comment]
Thanks for your tips. I understand your reason for that behavior, but I mostly have incomplete default values in my models. Your recommendations are working for me, that is good. 
I started to play with your library two days ago, and it looks constructive to me. I stay in testing it for my use cases, and I hope I could use it in production. Thanks for that and for your help again.
